sonar.projectKey=Manex142_POC-GPI2
sonar.organization=manex142
sonar.host.url=https://sonarcloud.io

sonar.java.binaries=**/target/classes
sonar.sources=authorization-server/src/main/java,resource-server/src/main/java
sonar.tests=authorization-server/src/test/java,resource-server/src/test/java